import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Control from "./Control";
import { apiUrl } from "@/lib/api";


export const metadata = {
  title: "Web",
  description: "Generated by 0520",
};





export default async function RootLayout({ children }) {
  const resp= await fetch(apiUrl("topics"),{cache:'no-store'});
  const topics = await resp.json();
  return (
    <html
    >
      <body>
      <h1><Link href="/">WEB</Link></h1>

      <ol>
      {topics.map((topic)=>{return<li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>}) }
      </ol>
      {children}
      <Control />
      </body>
    </html>
  );
}
